# Generated by Django 4.1.1 on 2022-11-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_rename_discountedprice_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='avatar.png', upload_to='addproduct'),
        ),
    ]
