# Generated by Django 4.1.1 on 2022-11-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
