# Generated by Django 4.1.1 on 2022-11-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seller',
        ),
    ]
